// src/constants/permissions.ts
import { RoleName } from '../types';

export const ROLE_PERMISSIONS: Record<RoleName, string[]> = {
  STUDENT: [
    'users:read:own',
    'users:update:self',
    'batches:read:own',
    'sessions:read:own',
    'attendance:mark:self',
    'attendance:read:own',
    'assessments:read:own',
    'feedback:read:own_received',
    'mentor_assignments:read:own',
    'risk_scores:read:own',
    'interventions:read:own',
    'notifications:read:own',
    'events:read:any',
    'event_registrations:create:self',
    'event_registrations:read:own',
    'proofs:submit:self',
    'proofs:read:own',
    'tasks:read:own',
    'tasks:update:own',
  ],
  TRAINER: [
    'users:read:own',
    'users:update:self',
    'batches:read:own',
    'sessions:create:batch',
    'sessions:update:batch',
    'sessions:read:own',
    'attendance:mark:batch',
    'attendance:read:batch',
    'attendance:update:batch',
    'attendance:export',
    'assessments:create:batch',
    'assessments:read:batch',
    'assessments:update:batch',
    'feedback:create:batch',
    'feedback:read:own_given',
    'risk_scores:read:category:batch',
    'risk_scores:calculate:batch',
    'notifications:read:own',
    'events:read:any',
    'proofs:read:batch',
    'proofs:approve:batch',
    'tasks:create:batch',
    'tasks:read:batch',
    'tasks:update:batch',
    'tasks:delete:batch',
    'tasks:grade:batch',
  ],
  FACULTY: [
    'users:read:own',
    'users:update:self',
    'users:read:any',
    'batches:read:any',
    'sessions:read:any',
    'attendance:read:any',
    'attendance:export',
    'assessments:read:any',
    'feedback:read:any',
    'mentor_assignments:read:any',
    'risk_scores:read:any',
    'interventions:read:any',
    'notifications:read:own',
    'events:read:any',
    'tasks:read:any',
  ],
  MENTOR: [
    'users:read:own',
    'users:update:self',
    'users:read:assigned',
    'batches:read:assigned',
    'sessions:read:assigned',
    'attendance:read:assigned',
    'assessments:read:assigned',
    'feedback:read:assigned',
    'mentor_assignments:read:own',
    'risk_scores:read:assigned',
    'interventions:create:assigned',
    'interventions:update:own',
    'interventions:log_outcome:own',
    'interventions:read:assigned',
    'notifications:read:own',
    'events:read:any',
  ],
  COORDINATOR: [
    'users:read:own',
    'users:update:self',
    'users:read:any',
    'batches:read:any',
    'sessions:read:any',
    'attendance:read:any',
    'attendance:export',
    'assessments:read:any',
    'risk_scores:read:any',
    'notifications:read:own',
    'events:create',
    'events:update:any',
    'events:read:any',
    'event_registrations:read:any',
    'proofs:read:any',
    'proofs:approve:any',
  ],
  ADMIN: [
    'users:create',
    'users:read:own',
    'users:update:self',
    'users:read:any',
    'users:update:any',
    'users:change_role',
    'users:activate',
    'users:recover_account',
    'batches:create',
    'batches:update:any',
    'batches:read:any',
    'sessions:read:any',
    'attendance:read:any',
    'attendance:update:any',
    'attendance:export',
    'assessments:read:any',
    'assessments:update:any',
    'feedback:read:any',
    'mentor_assignments:create',
    'mentor_assignments:read:any',
    'risk_scores:read:any',
    'risk_scores:calculate:any',
    'interventions:read:any',
    'notifications:read:own',
    'events:create',
    'events:update:any',
    'events:read:any',
    'event_registrations:read:any',
    'proofs:read:any',
    'proofs:approve:any',
    'tasks:create:any',
    'tasks:read:any',
    'tasks:update:any',
    'tasks:delete:any',
    'tasks:grade:any',
    'audit_logs:read',
  ],
};

export function hasPermission(role: RoleName | undefined, permissionCode: string): boolean {
  if (!role) return false;
  const list = ROLE_PERMISSIONS[role] || [];
  return list.includes(permissionCode);
}

export function hasAnyPermission(role: RoleName | undefined, ...permissionCodes: string[]): boolean {
  if (!role) return false;
  const list = ROLE_PERMISSIONS[role] || [];
  return permissionCodes.some((code) => list.includes(code));
}
